### ISSUE TITLE
Real-time updated content in PDF files

### ISSUE THREAD

**Issue by raphael-louis-andress** [pdf-association/pdf-issues#186] opened 2022-06-20 11:00 UTC
**Describe the bug**
1. Real-time updated content in PDF files. Because PDF files do not make it possible for the information to be updated. I believe the PDF file format is a great format, but if there was up-to-date information within the PDF file it would be better.
2. This could be done if the PDF file called a networking module of the operating system itself to execute http calls and thus have the content updated.

**Provide a recommendation for correction.**
- I would like to know everyone's opinion here if this idea is good or bad

**Additional context**
1.  I wish I had a way to reuse PDF files, usually PDF files consume a lot of disk space
2. This can be unsafe - could be a malware port
3. Imagine that you need to generate an updated pdf file every time - why, instead of generating an updated pdf file every time there is some trivial change, we can't just update the file itself without necessarily having to keep generating separate files with every trivial change ?

**References**
1. https://www.computerworld.com/article/2475900/the-adobe-reader-consumes-mass-quantities-of-hard-drive-space.html
4. https://www.bouldercounty.org/environment/recycle/reduce-reuse-recycle/
3. https://help.liferay.com/hc/en-us/articles/360044412992-How-to-resolve-Document-Library-PDF-previews-taking-up-more-disk-space-than-the-original-files
5. https://support.microsoft.com/en-us/windows/tips-to-free-up-drive-space-on-your-pc-4d97fc4a-0175-8d49-ac2f-bcf27de46d34
6. https://www.recordnations.com/articles/file-format-space/
7. http://www.customlivingsolutions.com/digitized-files-how-much-hard-drive-space-do-they-take-up
8. https://www.onelegal.com/blog/5-ways-to-reduce-the-size-of-a-pdf/
9. https://blog.flipsnack.com/5-ways-to-reduce-the-size-of-a-pdf-file/

**Comment by MatthiasValvekens** [comment] 2022-06-20 11:27
First off, I'm afraid this isn't an actionable erratum, i.e. there's no "broken" feature in the standard to fix. So this probably isn't the best place to discuss.

Putting on my iText hat: this is something we've thought about in the past, and there are various challenging aspects to this problem. I won't go into detail right here, but suffice to say that this is a minefield that needs to be navigated very carefully. :)

Also, there _might_ be a relevant talk on that topic at the upcoming PDF Days in September... ;).

**Comment by lrosenthol** [comment] 2022-06-20 13:51
As @MatthiasValvekens said, and I will put in a different way, this is not a bug but an actual *feature* of PDF.

PDF files represent (to the world at large) a "document" - which makes sense since that is what the "D" stands for ;).  User do *not* expect documents to change when they are viewed - either live while open or between opens.   Not only that, but most don't expect them to go anywhere near a network - hence why many viewers put up warning dialogs when a PDF tries to "phone home".

This is, of course, quite different from what users expect on the web - where content is entirely ephemeral and there it entirely based online and communication is core.

**Comment by lrosenthol** [comment] 2022-06-20 17:22
@raphael-louis-andress So you aren't talking about the content of a PDF being updated after it is distributed, but instead how one could manage an internal repository of documents.  That would seem to be the province of Document Management Systems (as their name implies).   But a DMS doesn't do document creation (in most cases, though there are exceptions in specialized fields) - such creation (or updating) must be done outside using tools such as the ones that you suggest.

And PDF creation is going to be based on the type of content that is being authored, with very different content layout and formatting needs.   Consider that the content authoring functionality of a word processing program (ala MSWord or Google Docs) is completely different from that of a spreadsheet (ala MSExcel or Google Sheets) and even more so from specialized authoring tools such as AutoCAD or MuseScore.   So trying to define such a system that would be "generic" seems impractical.

If you are looking for REST APIs for PDF creation. whether from markup languages such as JSON, XML or HTML or from existing authoring formats, you will find a number of them offered by members of the PDF Association.

**Comment by lrosenthol** [comment] 2022-06-20 19:37
PDF is standardized as ISO 32000.  Part 1 is for PDF 1.7 and Part 2 is for PDF 2.0.    Those documents are the official documentation on the PDF file format.

**Comment by MatthiasValvekens** [comment] 2022-06-20 20:31
Regarding this:

> @MatthiasValvekens Hi! when you say: "Putting on my iText hat:" ... do you mean: https://itextpdf.com/en?

I work for iText. What I meant is that _within the iText research team_ we've played around with the idea of "self-updating" PDF. I wanted to stress that that's completely orthogonal to anything in the PDF standard, since this issue tracker is really about resolving issues with the current spec. I should've made that distinction more clear.

Anyway, since you seem to be satisfied with the answers you got, I'll go ahead and close this, as you requested. :)

**Closed by MatthiasValvekens** 2022-06-20 20:31 UTC
Labels: enhancement
