### ISSUE TITLE
Clarification on signature field Lock dictionary permissions and DSS/DTS incremental updates

### ISSUE THREAD

**Issue by mkl-public** [pdf-association/pdf-issues#131] opened 2021-11-24 13:04 UTC
For certification signatures with _no-changes-allowed_ ISO 32000-2 clearly says that incremental updates with only DSS and/or DTS are allowed:

>_(Optional)_ The access permissions granted for this document. Changes to a PDF that are incremental updates which include only the data necessary to add DSS’s 12.8.4.3, "Document Security Store (DSS)" and/or document timestamps 12.8.5, "Document timestamp (DTS) dictionary" to the document shall not be considered as changes to the document as defined in the choices below.
>
>Valid values shall be:
>_1_ No changes to the document shall be permitted; any change to the document shall invalidate the signature.
>_2_ Permitted changes shall be filling in forms, instantiating page templates, and signing; other changes shall invalidate the signature.
>_3_ Permitted changes shall be the same as for 2, as well as annotation creation, deletion, and modification; other changes shall invalidate the signature.
>
>Default value: _2_.

*(Table 257 — Entries in the DocMDP transform parameters dictionary — entry for key **P**)*

(Last time I tried Adobe Acrobat still incorrectly reported such changes as invalidating the certification but Leonard had confirmed [here](https://issues.apache.org/jira/browse/PDFBOX-3017?focusedCommentId=17224930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17224930) that this is an Acrobat bug and will be addressed in a future release.)

But there is a second mechanism changing permissions to _no-changes-allowed_ via signatures, the signature field **Lock** dictionaries. Since PDF-2.0 these **Lock** dictionaries can contain a similar entry, also with the key **P**, but here DSS and DTS additions are not explicitly exempted; the full entry is:

>*(Optional; PDF 2.0)* The access permissions granted for this document. Valid values shall be:
>_1_ No changes to the document are permitted; any change to the document shall invalidate the signature.
>_2_ Permitted changes shall be filling in forms, instantiating page templates, and signing; other changes shall invalidate the signature.
>_3_ Permitted changes are the same as for 2, as well as annotation creation, deletion, and modification; other changes shall invalidate the signature.
>
>There is no default value; absence of this key shall result in no effect on signature validation rules.
>
>If **MDP** permission is already in effect from an earlier incremental save section or the original part of the document, the number shall specify permissions less than or equal to the permissions already in effect based on signatures earlier in the document. That is, permissions can be denied but not added. If the number specifies greater permissions than an **MDP** value already in effect, the new number is ignored.
>
>If the document does not have an author signature, the initial permissions in effect are those based on the number 3.
>
>The new permission applies to any incremental changes to the document following the signature of which this key is part.

*(Table 236 — Entries in a signature field lock dictionary — entry for key **P**)*

Apparently both entries work with the same underlying settings, the second one referring to the former value as the "_**MDP** permission already in effect from_ an earlier incremental save section or _the original part of the document_".

Thus, I have the impression that the _intent_ here is that the latter permission values shall have the same meaning as the former ones, they in particular also shall always allow DSS & DTS. On the other hand strict interpretation of the specification exempts DSS & DTP only when certifying, not when locking.

Which interpretation is correct? And could that interpretation made be clear in the specification?

**Comment by MatthiasValvekens** [comment] 2021-11-24 14:39
I can't speak to what the original intent was, but I would certainly hope that the respective interpretations of the DocMDP permission levels doesn't change depending on _where_ one happens to put them...

My guess is that the current wording is an artifact of how the PAdES requirements (against PDF 1.7) were merged into PDF 2.0. After all, the technical reasons that gave rise to the blanket DocMDP exemption for DTS/DSS updates in PAdES would apply equally to field lock dictionaries. So I would support amending this text to say explicitly that the rules are the same in both cases. I'll wait for more input before having a go at drafting some words, though.

--------

Issue #61 (which is still open) might also be useful to keep in mind while we review this, since the relation of the new *P* key to *FieldMDP* is also unclear and/or inconsistently implemented.

**Comment by MatthiasValvekens** [comment] 2021-11-30 10:19
Unless anyone objects to the above interpretation, I would suggest simply copying this tidbit from the **P** entry in Table 257, and inserting it after "The access permissions granted for this document." in the description of the **P** entry in Table 236:

> Changes to a PDF that are incremental updates which include only the data necessary to add DSS’s 12.8.4.3, "Document Security Store (DSS)" and/or document timestamps 12.8.5, "Document timestamp (DTS) dictionary" to the document shall not be considered as changes to the document as defined in the choices below.

This is technically a normative change, I suppose.

**Comment by petervwyatt** [comment] 2021-11-30 12:49
This is not my area of expertise, but the phrase "... only the data necessary ..." feels very imprecise. Can this include an updated Metadata stream or changed trailer keys? What if my specific workflow also requires a visual indicator that I deem as "necessary"? It feels to me that it would be better to be explicit about what kinds of PDF objects can / cannot be in said incremental update - this would then also be validatable from a file format PoV (in addition to the signature validation).

**Comment by MatthiasValvekens** [comment] 2021-11-30 12:55
I completely agree with that sentiment: incremental update validation is currently woefully underspecified. Unfortunately the problem is much more broad than DSS / DTS updates, and I don't think we _can_ address it properly here.

There's an ongoing ETSI project to sort all of that out properly (in which the PDFa's Digital Signatures TWG is also tangentially involved), but I'm not aware of any recent progress on that front.

**Comment by MatthiasValvekens** [comment] 2021-12-02 17:20
I've created a separate issue to discuss Peter's broader point, so we don't overload this one :). See #132.

**Comment by lrosenthol** [comment] 2021-12-02 19:38
The /P key in a Lock dictionary is 100% identical in handling to that of DocMDP, and it is implemented that way in "a well known implementation".

In terms of why the text doesn't reflect it, as @MatthiasValvekens said, the DSS/LTV work came out of ETSI while the locking bits came from Adobe Extension Level 3 and I missed coordinating them at the time.

**Comment by petervwyatt** [comment] 2021-12-02 21:30
PDF TWG agree text should be identical.

**Closed** 2021-12-07 01:34 UTC
Labels: bug, proposed solution

**Comment by mkl-public** [comment] 2023-11-13 12:55
@petervwyatt,

what exactly does the switch back and forth between the labels `ISO approved` and `ISO 32000-2 Amd1` indicate?

**Comment by petervwyatt** [comment] 2023-11-13 20:47
It's reflecting the changing status of what is happening with ISO 32000-2:2020 Amd1 (and I may have mistyped a few errata numbers when managing things). Currently only very few critical errata that are needed by PDF/A-4 dated revision, PDF/X-6 dated revision and ISO/TS 320005 supporting PDF/UA-2 will be included.

**Comment by mkl-public** [comment] 2023-11-14 17:18
Ok. How should implementors deal with "ISO approved" entries, and how with "ISO 32000-2 Amd1" entries? Shall they implement them? Should they implement them? May they implement them? Should they wait for them to be included in some published amendment?

**Comment by petervwyatt** [comment] 2023-11-15 01:04
All errata labelled as "ISO approved" have a fully reviewed and approved solution as published at https://pdf-issues.pdfa.org/ with total agreement from both the PDF Association's PDF TWG and ISO TC 171 SC 2 WG 8 experts - as indicated by the ISO logo appearing in the hover tooltip. I don't think things can get any more ratified or official than that! The fact that ISO no longer has appropriate pathways to correct highly technical documents is an issue with their choice of publishing model. This is also why the PDF Association provides the full set of all ratified solutions ("ISO approved") for free at https://pdf-issues.pdfa.org/. Content at this URL is actively maintained and, of course, you can always save the URL content to PDF for posterity (it has @media CSS for this purpose).

Note that this URL _also_ includes solutions that have been agreed by the PDF TWG, but are _not_ yet reviewed by ISO experts. There is a small risk that such solutions _might_ change during the ISO review process, if this process continues. Historically only minor wording changes to 2 errata were updated when ISO experts previously reviewed with the intent of the solution unchanged. Whether the implementers and vendors adopt those solutions is entirely up to them, the severity of the issue for them, the impact on their customers, their business model, etc.

**Comment by mkl-public** [comment] 2023-11-16 15:56
Ah, ok, thanks for the clarification! :)
