### ISSUE TITLE
Rendering Standards for Night Mode and Dark Mode in PDFs:

### ISSUE THREAD

**Issue by AmyLin2013** [pdf-association/pdf-issues#443] opened 2024-07-04 05:20 UTC
Night Mode and Dark Mode are widely used display options for PDFs. It is recommended that the PDF standard includes guidelines for rendering effects in these special modes. For example, applications like electronic flight bags (EFBs) have a significant demand for night mode. Establishing these guidelines will provide developers with the necessary guidance to ensure consistent effects across different applications.

**Comment by petervwyatt** [comment] 2024-07-04 05:45
Duplicate of #369 - please add any extra information or feedback to that issue.

**Closed by petervwyatt** 2024-07-04 05:45 UTC
Labels: bug
