### ISSUE TITLE
Common data structures (7.9): 'string' type contradiction

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#353] opened 2023-09-18 13:44 UTC
Table 35 (PDF data types) in 7.9.1 (General, Common data structures) confusingly declares `string` type as "Any string that is not a text string", *despite its dedicated subclause (7.9.2 (String object types)) defines string object as "further qualified as a text string, ASCII string, or byte string."*.

As [already emerged in a related issue](https://github.com/pdf-association/pdf-issues/issues/322#issuecomment-1674933919), for some obscure reason, that declaration has changed over time (`string` type was declared as plain simple "String object" till PDF 1.6 (see TABLE 3.31 (PDF data types))), inadvertently creating a rift between the current declaration in Table 35 ("Any string that is not a text string") and the current definition in subclause 7.9.2 ("a text string, ASCII string, or byte string").

### CORRECTION

IMHO, *the inconsistent declaration in Table 35 should be reverted to its original expression* (`string` type as "String object"), and *a new type should be introduced in Table 35 to unambiguously encompass all non-`text string` string types* ("Any string that is not a text string", ie `ASCII string` and `byte string`). As a consequence, all the `string`-typed dictionary entries conforming to this restrictive definition (such as `CheckSum` in Table 45) should be revised accordingly with the new data type.

**Comment by petervwyatt** [comment] 2023-09-19 02:01
It has been agreed that Table 35 is what is in error, as per your other errata, and that the more detailed sub-clauses are otherwise correct. The summary Table 35 provides will be corrected soon. Terminology from Figure 7 in subclause 7.9.2 is correct.

This is effectively a duplicate of #322.

**Closed by petervwyatt** 2023-09-19 02:01 UTC
Labels: bug
