### ISSUE TITLE
12.3.2.4 Named destinations cross reference to Table 202 should also include Tables 203 and 204

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#288] opened 2023-05-28 00:02 UTC
Clause 12.3.2.4 Named destinations, the last sentence in the para between NOTEs 1 and 2 states:

> The value of this entry shall be a dictionary in which each key is a destination name and the corresponding value is either an array defining the destination, using the syntax shown in "Table 149 — Destination syntax", or a dictionary with a **D** entry whose value is such an array and may optionally contain an **SD** entry as defined in "Table 201 — Action types".

The reference to Table 201 is incorrect as it is just the list of Action types, not all of which have **SD** keys. 

It should really be "Table 202 — Additional entries specific to a go-to action", Table 203 (Remote Go-To) or Table 204 (Embedded Go-To), as these are the only actions with an appropriate **D** entry.

**Comment by MatthiasValvekens** [comment] 2023-05-28 08:55
Isn't this a dupe of #162?

**Comment by petervwyatt** [comment] 2023-05-28 09:20
Yes-ish (thanks - that errata didn't make Amd1 and thus is not in the no-cost edition of 32K so I missed that we'd already addressed it! I need to go back to checking https://pdf-issues.pdfa.org/32000-2-2020/clause12.html#H12.3.2.4!)

But now I also notice that #162 only added the reference to GoTo actions (Table 202) and not GoToE (Table 203) or GoToR (Table 204). I believe both of these also meet the **D** and **SD** requirements and have not been excluded in previous versions of the PDF specification so they should be added as additional cross-references.

**Closed** 2023-06-01 22:50 UTC
Labels: bug, proposed solution
