### ISSUE TITLE
Wrong PDF version of Locked flag in annotations

### ISSUE THREAD

**Issue by MaximPlusov** [pdf-association/pdf-issues#332] opened 2023-08-25 14:39 UTC
Table 167 (Annotation flags) contains `PDF 1.4` for Locked flag. But it seems that this flag was actually introduced in PDF 1.5.

**Comment by petervwyatt** [comment] 2023-08-26 00:27
Adobe PDF 1.5 reference Table 8.12 says Locked was PDF 1.4 and ToggleNoView was PDF 1.5, but neither is mentioned in Adobe 1.4 Reference Table 8.11.

**Comment by mkl-public** [comment] 2023-08-28 09:13
There is an entry in the 1.4 Errata:

>Page 493, Table 8.11, Annotation flags: Add an entry for the following
flag, which was included in PDF 1.4 but was inadvertently omitted from
the specification:

>Bit position 8 -- Locked -- (PDF 1.4) If set, do not allow the
annotation to be deleted or its properties (including position and
size) to be modified by the user. However, this does not restrict
changes to the annotation's contents, such as a form field value. (See
implementation note in Appendix H.)

>The new implementation note is: "Acrobat 5 obeys the Locked flag only
for widget annotations."

**Comment by petervwyatt** [comment] 2023-08-29 00:03
Thank you @mkl-public! I get lazy and never check the errata :-)

Since this is now confirmed with official Adobe documentation, this issue is closed as "no fix" as the PDF 1.4 is correct.

**Closed by petervwyatt** 2023-08-29 00:03 UTC
Labels: wontfix
