### ISSUE TITLE
Annex Q misses transparency related entries in the annotation dictionary

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#104] opened 2021-07-13 14:43 UTC
Annex Q "Method for determining transparency on a page" mentions annotations in the last paragraph of Q.2, but does not address the effect of the following three entries in the annotation dictionary: **ca**, **CA**, **BM**.

As described in Table 166, these entries have slightly different effect for determining transparency on the page.

**BM** entry is used to blend the annotation appearance onto the page. Thus, any value other than **Normal** would imply the transparency of the page. I suggest to add this condition explicitly at the end of the last paragraph of Q.2.

**ca** and **CA** entries are used only to regenerate the appearance of the annotation. So, I would assume that they are already covered by the following three clauses:

- Q.2: All annotations object's in the page dictionary's **Annots** array shall have their appearance streams processed as a form XObject, according to Q.3, "Form XObjects"
- Q.3: the content stream of the form XObject shall be processed according to Q.2, "Page content"
- Q.2: **ca** / **CA** key is present [in the graphics state] and its value is less than one (1)

As an additional context, Annex Q is important for PDF/A-4, 6.2.9 "Transparency", which has format requirements based on the condition if the page contains transparency or not. I would also suggest to add a phrase in ISO 19005-4, 6.2.9 that explicitly references ISO 32000-2, Annex Q as the normative way for determining transparency on the page.

**Comment by petervwyatt** [comment] 2021-07-13 23:10
I believe this a duplicate of Issue #51 "Annex Q neglects new BM key for annotations" which has already been fixed at https://www.pdfa.org/pdf-issues/.

**Comment by petervwyatt** [comment] 2021-07-13 23:10
@bdoubrov please confirm so I can close.

**Comment by bdoubrov** [comment] 2021-07-14 07:29
@petervwyatt thanks, I didn't notice issue #51. I'd still like to reconfirm two other points, which were raised at PDFA TWG:
1) ca and CA entries don't need to be mentioned explicitly
2) adding an explicit reference to Annex Q in PDF/A-4

The second item is certainly relevant only for PDF/A-4 (and maybe also for PDF/X-6)

**Comment by petervwyatt** [comment] 2021-07-14 07:42
@bdoubrov Yes for point 1. ca/CA are already explicitly covered by subclasses Q.2 and Q.3 (yes, the wording is not the best and yes, the circular cross-referencing could be improved but the intent and explanation are sufficiently clear).

I suggest you take point 2 to the PDF/A TWG for resolution and then comment back here with any precisely worded resolution (and with an exact location) you'd like to see to ISO 19005-4:2020. I will then apply after the next PDF TWG meeting.

**Comment by petervwyatt** [comment] 2021-07-30 02:31
There is "no fix" for 32000-2.

Assigned to @bdoubrov as Chair of PDF/A TWG to decide if a fix to ISO 19005-4 to explicitly mention Annex Q is required.

**Comment by petervwyatt** [comment] 2021-09-27 08:13
@bdoubrov - did you discuss at the PDF/A TWG? Is there any correction to ISO 19005-4 the PDF/TWG wish to propose?

**Comment by bdoubrov** [comment] 2021-09-30 20:32
As per PDF/A TWG resolution, PDF/A-4 should indeed reference Annex Q as an algorithm to determine the transparency on the page.

**Comment by petervwyatt** [comment] 2021-10-31 23:04
@bdoubrov Could you please suggest where in ISO 19005-4:2020 you'd like to add that reference to Annex Q?

**Comment by bdoubrov** [comment] 2021-11-08 16:25
Add 

**Note 2.** Page transparency can be determined as defined in ISO 32000-2:2020, Annex Q. 

after 2nd par of 6.2.9.

**Comment by petervwyatt** [comment] 2021-11-08 23:59
https://pdf-issues.pdfa.org/19005-4-2020/clause06.html#H6.2.9

**Closed by petervwyatt** 2021-11-08 23:59 UTC
Labels: bug, duplicate, proposed solution, PDF/A-4
